import SearchHeader from '@/components/SearchHeader'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SearchLayout({ children }) {
  return (
    <div>
        <header>
            <SearchHeader/>
        </header>
        {children}
        {/* <Footer/> */}
    </div>
  )
}
